// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEZDnN_ljhDoJHLZ5_HllbMNqUau9m4E',
    appId: '1:266568990908:web:8e8a203af01f56d26e10b9',
    messagingSenderId: '266568990908',
    projectId: 'cloud-computing-lab-61a9c',
    authDomain: 'cloud-computing-lab-61a9c.firebaseapp.com',
    databaseURL: 'https://cloud-computing-lab-61a9c-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-computing-lab-61a9c.appspot.com',
    measurementId: 'G-LHLHTYF90F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlyuPiZo-1GUdGELMkLZ9Hu52gTmyDoY',
    appId: '1:266568990908:android:4f30cc102a6d95ce6e10b9',
    messagingSenderId: '266568990908',
    projectId: 'cloud-computing-lab-61a9c',
    databaseURL: 'https://cloud-computing-lab-61a9c-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-computing-lab-61a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP8oA5vO977dNzauYquCxM7wBkDQaDnaw',
    appId: '1:266568990908:ios:58997310aceec47d6e10b9',
    messagingSenderId: '266568990908',
    projectId: 'cloud-computing-lab-61a9c',
    databaseURL: 'https://cloud-computing-lab-61a9c-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-computing-lab-61a9c.appspot.com',
    iosBundleId: 'com.example.cloudComputing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP8oA5vO977dNzauYquCxM7wBkDQaDnaw',
    appId: '1:266568990908:ios:58997310aceec47d6e10b9',
    messagingSenderId: '266568990908',
    projectId: 'cloud-computing-lab-61a9c',
    databaseURL: 'https://cloud-computing-lab-61a9c-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-computing-lab-61a9c.appspot.com',
    iosBundleId: 'com.example.cloudComputing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBEZDnN_ljhDoJHLZ5_HllbMNqUau9m4E',
    appId: '1:266568990908:web:fc6e7258d69c4a9a6e10b9',
    messagingSenderId: '266568990908',
    projectId: 'cloud-computing-lab-61a9c',
    authDomain: 'cloud-computing-lab-61a9c.firebaseapp.com',
    databaseURL: 'https://cloud-computing-lab-61a9c-default-rtdb.firebaseio.com',
    storageBucket: 'cloud-computing-lab-61a9c.appspot.com',
    measurementId: 'G-5MXP3L93DS',
  );
}
